### ISSUE TITLE
Version 1.0.0 breaks existing mkdocs-localsearch installations

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/iframe-worker#481]
In v1.0.0, all occurrences of "polyfill" were renamed to "shim", including the unpkg URL:

Before:
```html
<script src="https://unpkg.com/iframe-worker/polyfill"></script>
```

After:

```html
<script src="https://unpkg.com/iframe-worker/shim"></script>
```

This breaks all existing installations of [mkdocs-localsearch](https://github.com/wilhelmer/mkdocs-localsearch) that use the old URL as documented in the [README](https://github.com/wilhelmer/mkdocs-localsearch/blob/master/README.md).

I'll update the README, but can we provide a workaround for existing installations?

Could we somehow redirect the old URL to the new one? Or else, provide the JS file in both folders for some time?

**Comment by squidfunk** [comment]
Thanks for reporting. That's expected, it's a major release after all. Workaround for existing installations is to use an explicit version smaller than 1, i.e. https://unpkg.com/iframe-worker@0.2.4/polyfill. I'm, not keen on providing the JS in two folders, as it doesn't motivate users to switch.

Additionally, localsearch can be deprecated as soon as Material for MkDocs 9 is out (when the funding goal is reached), as the offline plugin will automatically take care of integrating the correct version of iframe-worker.

**Comment by wilhelmer** [comment]
The problem is that it unexpectedly breaks all running projects TODAY without any explicit code changes. Of course, if there's a major version, breaking changes are expected, but you normally pin your dependencies to version 0.9.0 or whatever, test 1.0.0, and then upgrade when it's safe. That's not the case here.
 
This is probably 100% my fault because I didn't use an explicit version in the README. 

However, can't we still create two folders, only until the funding goal is reached? Pretty please 😢

**Comment by wilhelmer** [comment]
> It makes no sense to provide the fallback, as we'll only be dragging out the problem.

We'll be dragging out the problem until the amount of users affected by it is much lower, because they already switched to Material 9. That's the point.

But oh well, I'll put a note in the README and hope people will notice it. It's fine.

**Comment by squidfunk** [comment]
Compromise: if you find many people running into this problem, we can add it back.
