### ISSUE TITLE
Separate the iframe origin so that it can run in an alternate thread.

### ISSUE THREAD

**Issue by Patrick-ring-motive** [squidfunk/iframe-worker#522]
I would like to propose a few changes that would encourage the iframe to run in a separate thread. Many browsers have supported iframes of a different origin running in a [different thread](https://stackoverflow.com/questions/11510483/will-a-browser-give-an-iframe-a-separate-thread-for-javascript). I would suggest the following changes.

1. `iframe.setAttribute('sandbox','allow-scripts');` To tell browsers to allow scripts to run but [sandbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) the iframe as if it is from another origin.

 2. Encode the iframe src as a [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) if the browser supports it as those are typically treated as a separate origin.

3. Add `<script>try{let domain_split=document.domain.split('.');if(domain_split.length>1){document.domain=domain_split[domain_split.length-2]+'.'+domain_split[domain_split.length-1];}}catch(e){console.log(e);}</script>` to the head of the iframe document. This will attempt to change the domain from a subdomain to a root domain if possible.

**Comment by squidfunk** [comment]
Thanks for suggesting – that's actually very interesting. Could you craft a PR with your proposed changes, so we have something concrete to discuss and test?

**Comment by Patrick-ring-motive** [comment]
I find someone else trying to do this a [while back](https://stackoverflow.com/questions/30558817/how-to-create-a-worker-in-a-sandboxed-iframe). I'll create a PR today or tomorrow. The main reason for all of the different methods to do the same thing is different browser support.

1. `sandbox="allow-scripts"` property for iframes looks well supported now for most browsers and this is probably all you need unless you get into some pre-2015 browsers.
2. Data URIs have been supported since 2005 but different browsers have historically had different opinions about whether or not they should be treated as same-origin. Currently most treat them as different origin which helps with this.
3. This code snippet changes the iframe domain from a subdomain to a parent domain if it is allowed to. This consequently causes the iframe to be treated as a different origin. I haven't been able to test if this spawn a new thread though so possibly not useful. Only really necessary if the browser doesn't support option 1 or option 2.


I also left out a couple of possibilities that don't seem immediately useful. 

4. Blob URLs are also sometimes treated as same-origin and sometimes not. I think all browsers that support blob URLs have the sandbox option though.
5. Setting CSP to [sandbox](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox) but this is easier with the iframe attribute.
6. Serving iframe over http instead of https is sometimes considered a different origin. Obvious security problems.

The whole goal of all this is to force the iframe to be treated as from a separate origin. You could even go so far as to host a page on a different domain.

**Comment by squidfunk** [comment]
Thanks for the details. So my primary use case of this project is actually shimming web workers on `file://` locations. It is absolutely essential that this still [works in all browsers](https://squidfunk.github.io/mkdocs-material/browser-support/) that the project I've written this little library supports.

Unfortunately, I'm not sure whether I'm able to test all of them.

**Comment by Patrick-ring-motive** [comment]
I’ll remove the inline script for option 3. Not needed for your supported browsers.

**Comment by squidfunk** [comment]
Thanks! I'll look into it asap. Just curious, what are you using `iframe-worker` for? I primarily wrote it for Material for MkDocs, but always good to learn about further use cases.

**Comment by Patrick-ring-motive** [comment]
I'm not using it yet. I was looking for a solution to implement [partytown](https://partytown.builder.io/) on older browsers and I had the idea for iframes with alternate threads. I had guessed someone had already implemented something similar and research led me to this project. It doesn't exactly line up with your `file://` use case so I may have to make changes but it is very close and I'd rather not start from scratch. I can't discuss use cases at my day job. The primary use outside of work is better performance related to partytown and [qwik](https://qwik.builder.io/). [This project](https://github.com/Patrick-ring-motive/wellStreetJournal) is the first target for my performance optimizations but I haven't implemented web workers there yet. I need to expand this to service workers next but I haven't figured that out yet.

**Comment by Patrick-ring-motive** [comment]
Trying to test this out and I’m having trouble. It may not work with this project. I think I’ll be better building my own implementation from scratch. You can close this if you want.

**Comment by squidfunk** [comment]
I'll check it as soon as I find some time! Many thanks for your work so far, I wasn't aware of the fact that iframes can run in a separate thread. Maybe there's a way to make this work with `file://`.

**Comment by squidfunk** [comment]
Closing for the reasons stated in https://github.com/squidfunk/iframe-worker/pull/523#issuecomment-1423010279.
